- name: install development environment with custom configuration for a dev machine
  hosts: all 
  roles:
    - role: githubixx.kubectl
    - role: buildAgent
    - role: gantsign.helm
  vars:  
   # Where to install "kubectl" binary
    kubectl_bin_directory: "/usr/local/bin"
    # Directory to store the kubectl archive
    kubectl_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
    # Owner of "kubectl" binary
    kubectl_owner: "root"
    kubectl_binary_mode: "0755"
    helm_version: '3.9.4'

  become: yes
  become_method: sudo 