---

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes update_cache=yes cache_valid_time=3600
  become: true 

- name: add common libs
  apt:
      name:
       - jq
      state: latest
      update_cache: yes 
  become: true    

- name: Install yq for yaml parsing.
  community.general.snap:
    name:
      - yq
  become: true    