---

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes update_cache=yes cache_valid_time=3600
  become: true 

- name: add common libs
  apt:
      name:
       - jq
      state: latest
      update_cache: yes 
  become: true    

- name: Install Helm S3 Plugin
  kubernetes.core.helm_plugin:
    plugin_version: v0.14.0
    plugin_path: https://github.com/hypnoglow/helm-s3
    state: present