---
# This installs the Pi-Hole Runner for github

- name: stop services
  ansible.builtin.debug:
    msg: "Deregister Services"
  notify:
    - "stop services"
    - "unregister blog"
    - "unregister monitoring"
    - "unregister pihole"
  when: destroy == true

- name: Make directory for action runner if not exist
  file:
      path: "{{ github_action_installation_dir }}"
      state: directory
      owner: "{{ github_runtime_user }}"
      group: "{{ github_runtime_user }}"
  become: true
  when: destroy == false

- name: Download the runner binary
  ansible.builtin.get_url:
    url: "https://github.com/actions/runner/releases/download/v{{ github_linux_runner_version }}/actions-runner-linux-x64-{{ github_linux_runner_version }}.tar.gz"
    dest: "{{ github_action_installation_dir }}/actions-runner-linux-{{ github_linux_runner_version }}.tar.gz"
  when: destroy == false

- name: Get sha256 of file
  ansible.builtin.stat:
    path: "{{ github_action_installation_dir }}/actions-runner-linux-{{ github_linux_runner_version }}.tar.gz"
    checksum_algorithm: sha256
    get_checksum: yes
  register: sha256
  when: destroy == false

# - name: debug checksum
#   ansible.builtin.debug:
#     msg: sha256.stat.checksum
#   when: destroy == false

# - name: Verify sha256sum of script before execution.
#   fail:
#     msg: "Failure, runner checksum does not match."
#   when:
#      - sha256.stat.checksum != github_linux_runner_checksum
#      - destroy == false