---

- name: Install Helm S3 Plugin
  kubernetes.core.helm_plugin:
    plugin_version: v0.14.0
    plugin_path: https://github.com/hypnoglow/helm-s3
    state: present
  become_user: "{{ github_runtime_user }}"

- name: Add a repository
  kubernetes.core.helm_repository:
    name: "{{ item.key }} "
    repo_url: "{{ item.value }}"
  loop: "{{ repositories | dict2items }}"  
  vars:
        repositories:
            metallb : "s3://df-helmchart-repo/charts/metallb"
            blog    : "s3://df-helmchart-repo/charts/blog"
  become_user: "{{ github_runtime_user }}"          