---
- name: copy the kube profile to the user directory.
  ansible.builtin.copy:
      src: .kube
      dest: /home/vagrant/
      owner: "{{ github_runtime_user }}"
      group: "{{ github_runtime_user }}"
      directory_mode: 0400
      mode:  0400